name: Deploy with Vapor
on:
  push:
    branches: [ staging, production ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vapor
        run: composer global require laravel/vapor-cli
      - name: Install dependencies now needed for vapor
        run: composer install
        env:
          PUSHER_APP_ID: ' '
          PUSHER_APP_KEY: ' '
          PUSHER_APP_SECRET: ' '
      - name: Deploy With vapor
        run: /home/runner/.composer/vendor/bin/vapor deploy ${GITHUB_REF##*/} --commit="${GITHUB_SHA}" --message="${GITHUB_MESSAGE}"
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
          PUSHER_APP_ID: ' '
          PUSHER_APP_KEY: ' '
          PUSHER_APP_SECRET: ' '
